services:
  silownia_redis:
    container_name: redis_server
    image: "redis:alpine"
    ports:
      - "6379:6379"

  silownia_db:
    container_name: database_server
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: silownia

  silownia_api:
    build:
      context: ./backend
    container_name: backend_server
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      silownia_db:
        condition: service_healthy

  silownia_frontend:
    build:
      context: ./frontend
    container_name: frontend_server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata: {}
